import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: "#F5F5F5",
  },
  input: {
    height: 40,
    borderColor: "#CCC",
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 12,
    paddingHorizontal: 12,
    backgroundColor: "#FFF",
  },
  searchInput: {
    height: 40,
    borderColor: "#CCC",
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 12,
    paddingHorizontal: 12,
    backgroundColor: "#FFF",
  },
  picker: {
    height: 40,
    width: "100%",
    borderColor: "#CCC",
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 12,
    backgroundColor: "#FFF",
    paddingHorizontal: 8,
  },
  item: {
    flexDirection: "column",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#DDD",
    backgroundColor: "#FFF",
    borderRadius: 8,
    marginBottom: 8,
  },
  image: {
    width: "100%",
    height: 150,
    resizeMode: "contain",
    borderRadius: 8,
    marginBottom: 12,
  },
  text: {
    fontSize: 16,
    color: "#333",
    marginBottom: 4,
  },
  redText: {
    color: "#DC143C",
    marginTop: 8,
    fontSize: 16,
  },
  listEmptyText: {
    textAlign: "center",
    marginTop: 20,
    color: "#666",
    fontSize: 16,
  },
  addButton: {
    marginTop: 20,
    padding: 16,
    backgroundColor: "#4682B4",
    borderRadius: 8,
    alignItems: "center",
  },
  addButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 16,
    textAlign: "center",
  },
  form: {
    marginBottom: 24,
    marginTop: 12,
  },
  backText: {
    color: "#4682B4",
    marginTop: 16,
    fontSize: 18,
  },
  viewListButton: {
    marginTop: 24,
    padding: 12,
    backgroundColor: "#B0BEC5",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#90A4AE",
    alignItems: "center",
  },
  viewListButtonText: {
    color: "#37474F",
    fontSize: 14,
  },
});
